# Informações gerais {#cap1}




## Eventos realizados com os jovens cientistas

```{r calendar_JCs1, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE}

# Jovens Cientistas 
diagnostico_cd_FREQ_JC <- read_csv("data/diagnostico_cd - FREQ_JC.csv")
# Novos Jovens Cientistas
diagnostico_cd_FREQ_NJC <- read_csv("data/diagnostico_cd - FREQ_NJC.csv")

diagnostico_cd_EVENTOS <- read_csv("data/diagnostico_cd - EVENTOS.csv", 
                                   col_names = FALSE, col_types = cols(X2 = col_date(format = "%d/%m/%Y")))

diagnostico_cd_EVENTOS %<>% mutate(eventos = as.factor(X3))
#diagnostico_cd_EVENTOS %<>% mutate(eventos = unclass(eventos))
diagnostico_cd_EVENTOS %<>% mutate(CD = ifelse(eventos=="CD",1,NA))
diagnostico_cd_EVENTOS %<>% mutate(G = ifelse(eventos=="G",2,NA))
diagnostico_cd_EVENTOS %<>% mutate(IA = ifelse(eventos=="IA",3,NA))
diagnostico_cd_EVENTOS %<>% mutate(OFICINA = ifelse(eventos=="OFICINA",4,NA))
diagnostico_cd_EVENTOS %<>% mutate(PAL = ifelse(eventos=="PAL",5,NA))
diagnostico_cd_EVENTOS %<>% mutate(PG = ifelse(eventos=="PG",6,NA))
diagnostico_cd_EVENTOS %<>% mutate(PI = ifelse(eventos=="PI",7,NA))


#dflegenda <- data.frame(labels=levels(as.factor(diagnostico_cd_EVENTOS$X3)),
#                       valores=levels(as.factor(diagnostico_cd_EVENTOS$eventos)))
diagnostico_cd_EVENTOS <- as.data.frame(diagnostico_cd_EVENTOS)
row.names(diagnostico_cd_EVENTOS) <- as.vector(paste(diagnostico_cd_EVENTOS$X3,seq(1:length(diagnostico_cd_EVENTOS$X3))))

diagnostico_cd_EVENTOS <- tibble::as_tibble(diagnostico_cd_EVENTOS)


diagnostico_cd_EVENTOS %<>% mutate(eventos_ = as.numeric(eventos))


diagnostico_cd_EVENTOS %>% arrange(eventos) |>
  group_by(X3) |>
  e_charts(X2) |> 
  e_calendar(range = c("2021-01-01", "2021-06-30")) |>
#  e_calendar(range = c("2021-07-01", "2021-12-31"),top="260") |>
#  e_calendar(range = c("2021")) |> 
  e_heatmap(eventos_, coord_system = "calendar") |>
  e_color(c("#4a82a8","#fed26e","#7faed2","#a094e1","#dc6f6c","#62acd1","#8bc6d2")) |>
  e_heatmap(X3, coord_system = "calendar",label = list(normal = list(show = TRUE))) |>
  e_tooltip(trigger = c("item","axis")) |>
  e_title("Eventos 1º SEM", "JC")
  
  
 diagnostico_cd_EVENTOS %>% arrange(eventos) |>
   group_by(X3) |>
   e_charts(X2) |> 
   e_calendar(range = c("2021-07-01", "2021-12-31")) |>
# #  e_calendar(range = c("2021")) |> 
   e_heatmap(eventos_, coord_system = "calendar") |>
   e_color(c("#4a82a8","#fed26e","#7faed2","#a094e1","#dc6f6c","#62acd1","#8bc6d2")) |>
   e_heatmap(X3, coord_system = "calendar",label = list(normal = list(show = TRUE))) |>
   e_tooltip(trigger = c("item","axis")) |>
   e_title("Eventos 2º SEM", "JC")

```


```{r setores_JC, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE}

# Jovens Cientistas 
diagnostico_cd_FREQ_JC <- read_csv("data/diagnostico_cd - FREQ_JC.csv")
# Novos Jovens Cientistas
diagnostico_cd_FREQ_NJC <- read_csv("data/diagnostico_cd - FREQ_NJC.csv")

diagnostico_cd_EVENTOS <- read_csv("data/diagnostico_cd - EVENTOS.csv", 
                                   col_names = FALSE, col_types = cols(X2 = col_date(format = "%d/%m/%Y")))

diagnostico_cd_EVENTOS %<>% mutate(eventos = as.factor(X3))
#diagnostico_cd_EVENTOS %<>% mutate(eventos = unclass(eventos))
diagnostico_cd_EVENTOS %<>% mutate(CD = ifelse(eventos=="CD",1,NA))
diagnostico_cd_EVENTOS %<>% mutate(G = ifelse(eventos=="G",2,NA))
diagnostico_cd_EVENTOS %<>% mutate(IA = ifelse(eventos=="IA",3,NA))
diagnostico_cd_EVENTOS %<>% mutate(OFICINA = ifelse(eventos=="OFICINA",4,NA))
diagnostico_cd_EVENTOS %<>% mutate(PAL = ifelse(eventos=="PAL",5,NA))
diagnostico_cd_EVENTOS %<>% mutate(PG = ifelse(eventos=="PG",6,NA))
diagnostico_cd_EVENTOS %<>% mutate(PI = ifelse(eventos=="PI",7,NA))




#dflegenda <- data.frame(labels=levels(as.factor(diagnostico_cd_EVENTOS$X3)),
#                       valores=levels(as.factor(diagnostico_cd_EVENTOS$eventos)))
diagnostico_cd_EVENTOS <- as.data.frame(diagnostico_cd_EVENTOS)
row.names(diagnostico_cd_EVENTOS) <- as.vector(paste(diagnostico_cd_EVENTOS$X3,seq(1:length(diagnostico_cd_EVENTOS$X3))))

diagnostico_cd_EVENTOS <- tibble::as_tibble(diagnostico_cd_EVENTOS)


diagnostico_cd_EVENTOS %<>% mutate(eventos_ = as.numeric(eventos))

#diagnostico_cd_EVENTOS %>% arrange(eventos) %>%
#    group_by(X3) %>% 
#   summarise(n=n()) %>% 
#      group_by(X3) |>
#      e_charts(X3) |> 
#      e_color(c("#4a82a8","#fed26e","#7faed2","#a094e1","#dc6f6c","#62acd1","#8bc6d2")) |>
#      e_bar(n)  


diagnostico_cd_EVENTOS %>% 
      arrange(eventos) %>% 
          group_by(X3) %>% 
          filter(X3 %in% c("CD","G","IA","OFICINA","PAL","PG","PI")) %>% 
          summarise(n = n())  %>% 
        head() |> 
        e_charts(X3) |>
        e_color(c("#4a82a8","#fed26e","#7faed2","#a094e1","#dc6f6c","#62acd1","#8bc6d2")) |>
        e_pie(n)


```


## Encontro com os novos jovens cientistas 




```{r calendar_NJCs1, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE}


diagnostico_cd_EVENTOS_NJC <- read_csv("data/diagnostico_cd - EVENTOS_NJC.csv",
                                   col_names = FALSE, col_types = cols(X2 = col_date(format = "%d/%m/%Y")))


diagnostico_cd_EVENTOS_NJC %<>% mutate(eventos = as.factor(X3))
#diagnostico_cd_EVENTOS_NJC %<>% mutate(eventos = unclass(eventos))
diagnostico_cd_EVENTOS_NJC %<>% mutate(CD = ifelse(eventos=="CD",1,NA))
diagnostico_cd_EVENTOS_NJC %<>% mutate(G = ifelse(eventos=="G",2,NA))
diagnostico_cd_EVENTOS_NJC %<>% mutate(IA = ifelse(eventos=="IA",3,NA))
diagnostico_cd_EVENTOS_NJC %<>% mutate(OFICINA = ifelse(eventos=="OFICINA",4,NA))
diagnostico_cd_EVENTOS_NJC %<>% mutate(PAL = ifelse(eventos=="PAL",5,NA))
diagnostico_cd_EVENTOS_NJC %<>% mutate(PG = ifelse(eventos=="PG",6,NA))
diagnostico_cd_EVENTOS_NJC %<>% mutate(PI = ifelse(eventos=="PI",7,NA))


diagnostico_cd_EVENTOS_NJC <- as.data.frame(diagnostico_cd_EVENTOS_NJC)
row.names(diagnostico_cd_EVENTOS_NJC) <- as.vector(paste(diagnostico_cd_EVENTOS_NJC$X3,seq(1:length(diagnostico_cd_EVENTOS_NJC$X3))))

diagnostico_cd_EVENTOS_NJC <- tibble::as_tibble(diagnostico_cd_EVENTOS_NJC)


diagnostico_cd_EVENTOS_NJC %<>% mutate(eventos_ = as.numeric(eventos))

diagnostico_cd_EVENTOS_NJC %>% arrange(eventos) %>%  
  filter(X3 %in% c("CD","IA","OFICINA","PAL","PG","PI")) |>
  group_by(X3) |>
  e_charts(X2) |>
  e_calendar(range = c("2021-01-01", "2021-06-30")) |>
  e_heatmap(eventos_, coord_system = "calendar") |>
  e_color(c("#4a82a8","#7faed2","#a094e1","#dc6f6c","#62acd1","#8bc6d2")) |>
  e_heatmap(X3, coord_system = "calendar",label = list(normal = list(show = TRUE))) |>
  e_tooltip(trigger = c("item","axis")) |>
  #e_visual_map(max = 7) |>
  #e_legend(type = "plain",show = TRUE)|>
  #e_labels() |>
  e_title("Eventos 1° SEM", "NJC")

# remocao da cor ,"#fed26e" pois não tem "G"




  diagnostico_cd_EVENTOS_NJC %>% arrange(eventos) %>%  
  filter(X3 %in% c("CD","IA","OFICINA","PAL","PG","PI")) |>
  group_by(X3) |>
  e_charts(X2) |>
  e_calendar(range = c("2021-07-01", "2021-12-31")) |>
  e_heatmap(eventos_, coord_system = "calendar") |>
  e_color(c("#4a82a8","#7faed2","#a094e1","#dc6f6c","#62acd1","#8bc6d2")) |>
  e_heatmap(X3, coord_system = "calendar",label = list(normal = list(show = TRUE))) |>
  e_tooltip(trigger = c("item","axis")) |>
  #e_visual_map(max = 7) |>
  #e_legend(type = "plain",show = TRUE)|>
  #e_labels() |>
  e_title("Eventos 2º SEM", "NJC")
  

```


```{r setores_NJC, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE}

diagnostico_cd_EVENTOS_NJC <- read_csv("data/diagnostico_cd - EVENTOS_NJC.csv", 
                                   col_names = FALSE, col_types = cols(X2 = col_date(format = "%d/%m/%Y")))

diagnostico_cd_EVENTOS_NJC %<>% mutate(eventos = as.factor(X3))
#diagnostico_cd_EVENTOS_NJC %<>% mutate(eventos = unclass(eventos))
diagnostico_cd_EVENTOS_NJC %<>% mutate(CD = ifelse(eventos=="CD",1,NA))
diagnostico_cd_EVENTOS_NJC %<>% mutate(G = ifelse(eventos=="G",2,NA))
diagnostico_cd_EVENTOS_NJC %<>% mutate(IA = ifelse(eventos=="IA",3,NA))
diagnostico_cd_EVENTOS_NJC %<>% mutate(OFICINA = ifelse(eventos=="OFICINA",4,NA))
diagnostico_cd_EVENTOS_NJC %<>% mutate(PAL = ifelse(eventos=="PAL",5,NA))
diagnostico_cd_EVENTOS_NJC %<>% mutate(PG = ifelse(eventos=="PG",6,NA))
diagnostico_cd_EVENTOS_NJC %<>% mutate(PI = ifelse(eventos=="PI",7,NA))



diagnostico_cd_EVENTOS_NJC <- as.data.frame(diagnostico_cd_EVENTOS_NJC)
row.names(diagnostico_cd_EVENTOS_NJC) <- as.vector(paste(diagnostico_cd_EVENTOS_NJC$X3,seq(1:length(diagnostico_cd_EVENTOS_NJC$X3))))

diagnostico_cd_EVENTOS_NJC <- tibble::as_tibble(diagnostico_cd_EVENTOS_NJC)


diagnostico_cd_EVENTOS_NJC %<>% mutate(eventos_ = as.numeric(eventos))

diagnostico_cd_EVENTOS_NJC %>% 
  arrange(eventos) %>% 
  group_by(X3) %>% 
  filter(X3 %in% c("CD","IA","OFICINA","PAL","PG","PI")) %>% 
  summarise(n = n())  %>% 
  head() |> 
  e_charts(X3) |> 
  e_color(c("#4a82a8","#7faed2","#a094e1","#dc6f6c","#62acd1","#8bc6d2")) |> 
  e_pie(n)

# remocao da cor ,"#fed26e" pois não tem "G"
```




