# Relatório de Inteligência Artificial {#cap3}


A disciplina "Inteligência artificial, a divertida mente das máquinas" imerge no universo da 
inteligência artificial através da experimentação e interação com ferramentas gratuitas e de fácil 
acesso. Sendo assim, o ensino-aprendizagem é conduzido de maneira lúdica com a confecção e interação 
com jogos e algoritmos baseados nos conceitos de inteligência artificial presentes nos dias atuais. 
Para tanto, propõe-se a estimulação do senso crítico e investigativo dos alunos através da proposição 
de soluções para problemas da escola e comunidade local com o auxílio da inteligência artificial, 
permitindo um contato direto com sua realidade e desmistificando a complexidade das tecnologias 
envolvidas nessa área. 

## Introdução à Inteligência Artificial 

### Experiência - Jovens Cientistas

O encontro foi realizado com uma proposta inicial 
da ideia de Inteligência Artificial (IA) por meio de 
diálogo, no qual os estudantes foram 
estimulados a ter a primeira noção 
sobre o tema e compreender o seu campo aplicação. 

Alguns estudantes reveleram o seu desconhecimento sobre o tema. 
O instrutor aproveitou uma atividade lúdica, de cunho experimental, 
interativo e individual para experimentar o uso desse tipo de IA. 
Trata-se de um recurso do google 
que solicita que você utilize os dedos para desenhar
numa lousa *touch screen* a partir do fornecimento de 
uma palavra chave de objetos como mesa, relógio, carro,
flechas, barcos ou de pessoas e animais. O link dessa 
ferramenta ([Quick Draw!](https://quickdraw.withgoogle.com/))
foi disponibilizado aos estudantes. A página 
faz uma provocação ao usuário,

**"Será que uma rede neural consegue aprender a reconhecer seus desenhos?"**, 

a partir desse texto, o instrutor mergulha em mais 
provocações aos estudantes, explorando a ideia da palavra neural
e sua inspiração no campo da biologia. 
É discutida a capacidade da máquina aprender, ainda 
sem relativizar a relação entre a inteligência humana e 
de máquina. Então é sugerido o teste da ferramenta 
para o que estudante possa avaliar se fato a máquina 
pode ou não aprender com os desenhos de uma pessoa. 
Cada estudante com seu link foi submetido a palavras 
diferentes de forma automática pela ferramenta e 
tiveram 20 segundos para desenhar cada proposta. 
A medida que o desenho é realizado e você confirma 
que a ferramenta acertou, a rede neural 
recebe um reforço pela confirmação do acerto. 
Essa dinâmica  foi proposta como uma ideia 
de diversão, de jogo. Foi demonstrado aos 
estudantes que os desenhos que  a rede neural 
não conseguiu adivinhar pode ainda 
ser estudado. Assim, a partir 
dessa análise o estudante começa a compreender 
que há um grande banco de imagens de referência 
que a ferramenta utiliza para tentar adivinhar
e que ela usa uma análise de semelhança 
para reconhecer qual é o objeto idealizado 
por trás do esboço feito pelo usuário. Um esboço 
com pouco especificidade pode gerar confusão para 
a rede neural. 
Em seguida, foi explicado que a máquina precisa 
de um conjunto de exemplos para aprender 
o que são os objetos e diante da apresentação 
de vários exemplos parecidos temos um certo limite 
para reconhecer um objeto. 
O instrutor ainda provoca o exercício de demonstrar 
esta atividade para algum parente e questioná-lo 
se é uma pessoa que está adivinhando ou máquina. 

Neste ponto do encontro os estudantes ficaram 
mais abertos a interação, relataram 
a ideia de que em alguns jogos há um robô 
inteligente competindo contra eles. Outra 
estudante espontaneamente traz a palavra 
algorítimo para o diálogo, revelando 
a conexão da ideia do aprendizado de máquina
a uma série de regras e procedimentos 
que mimetizam uma forma de aprendizado. 

Ao final desta etapa, foi proposto 
que cada estudante indicasse 
o número de acertos que a ferramenta 
alcançou, utilizando uma   ferramenta 
do [slido](slido.com)  que centraliza as respostas  
e constrói um histograma. A partir deste conjunto 
os estudantes foram estimulados a discutir
por uma perspectiva estatística 
sobre a capacidade da máquina de  
inferir a definição do desenho por meio
do esboço. 

É importante salientar que este pequeno 
experimento promove aos estudante 
uma visão completa de aprendizado 
supervisionado, ainda que não tenha 
permeado por conteúdos matemáticos e estatísticos1
avançados. Apenas a interface, a ideia de comparação, 
similiaridade , reconhecimento e pouco de analogia 
ao comportamento de aprendizado biológico, permitiram 
que o estudante desenvolvesse esses elementos cognitivos 
da inteligência artificial. 


Depois de ter experimentado a ferramenta os estudantes 
começaram a escrever no chat porque a rede neural acerta ou erra:

 - "Ela acerta porque já viu o desenho antes!". 
 - "Erra porque o desenho não foi bem feito!". 
 - "Ela erra porque não tem conhecimento sobre aquilo que foi demonstrado!"
 
 O instrutor explorou um dos desenhos, mostrando que para que um determinado 
 desenho fosse reconhecido era necessário que ele mantivesse características 
 presentes nos desenhos que compõem o banco de imagens de referência 
 da rede neural. Também foi demonstrado que se algumas características fogem 
 do padrão, mas se assemelham a outro objeto pode levar a classificação 
 equivocada do objeto, também percebido anteriormente por uam das estudantes.
 
 A medida que o encontro evoluiu, o vocabulário de área de inteligência artificial 
 foi sendo introduzido e argumentação dos estudantes começou a ser baseada 
 nestes termos. 
 
 O instrututor ainda destaca que para uma imagem pertencer ao banco de imagens 
 de referência é necessário que muitas pessoas tenham desenhado de forma 
 similar, o que torna esta imagem elegível ao banco de dados.
 
 Neste novo ciclo do encontro, o instrutor novamente explora a análise 
 crítica dos estudantes, pedindo para votarem a respeito da capacidade 
 da IA ser uma boa juíza sobre desenhos. A maioiria votou que a IA 
 seria uma excelente juíza de desenhos.
 Na avaliação por chat de um dos estudantes a inteligência artificial 
 não tem conhecimento sobre alguns detalhes e portanto não mereceria 
 uma nota excelente para julgar esta atividade. Chegando a conclusão 
 que ela não é perfeita. 
 
 Vocábulos como: 
 
 - treina;
 - acerta; 
 - erra; 
 - aprende; 
 - imitar;
 - modelo;
 - engrenagem;
 - algorítimo;
 - rede neural; 
 
 ajudam na definição mais formal da inteligência artificial: 
 
 **É a capacidade da máquina funcionar de maneira ao raciocínio humano.**
 
 **Aprendizagem de máquina basea-se na capacidade de aprender com os dados.**
 
 Ainda nesta etapa, por meio [slido](slido.com), os estudantes foram estimulados a
 indicar  palavras para gerar  nuvem de palavras a respeito das
 aplicações de IA. Algumas palavras escolhidas pelos estudantes 
 chamaram atenção como "Celular", "Redes Sociais", "Facebook", "Youtube", "Netflix" e 
 "Intagram", "Xbox" e "Internet". Devido ao universo de palavras, as questões 
 sobre o sistema de recomendações emergiram, de forma similar a discussão gerada 
 na discipliana de Ciência de  Dados. O  instrututor ainda comenta que as 50 milhões do Google  
 estão disponíveis para o desenvolvimento de variadas aplicações. 
 
 
 A última demonstração do encontro consistiu na apresentação do 
 [Scratch](https://hackeduca.github.io/) numa versão mais avançada que aquela experimentada 
 pelos estudantes no ano anterior. O instrutor demonstrou alguns ambientes e  
 funcionalidades do Scratch. Especialmente foi apresentado a possibilidade 
 de desenvolver uma aplicação de IA utilizando o   *TensorFlow K-NN*
 sendo a atividade foco do encontro de retomada da próxima aula.
 
### Experiência Novos Jovens Cientistas

A aula de introdução de IA realizada com os Novos Jovens Cientistas sofreu
alterações em relação a primeira aula realizada com o grupo Jovens Cientistas (JC). 
As primeiras etapas foram guiadas da mesma maneira, entretanto, 
depois de todo ciclo com [Quick Draw!](https://quickdraw.withgoogle.com/)
foi inserido um debate a respeito da força da inteligência artificial. 

É demonstrado que a inteligência artificial fraca tem alta capacidade 
de realizar atividades especificas, enquanto que a ideia de uma inteligência 
artificial forte está ligada a capacidade de assimilar, classificar e 
produzir uma série de conteúdos e informações. Este paralelo 
envolveu os estudantes num intenso debate, ao ponto 
deles se comportarem de maneira muito confortável, 
buscando referência nos seus filmes favoritos, por exemplo, "Vingadores". 
Eles começaram a formular diversas situações nas quais equipamentos 
pudessem ter inteligência artificial forte  ao ponto inclusive 
de reinvindicarem respeito. 

Uma outra mudança do encontro dos NJC em relação ao realizado com JC 
que deixou alguns estudantes surpresos foi a capacidade do 
[Google Assistente](https://assistant.google.com/intl/pt_br/)
em agendar compromissos pelo usuário, simulando que é 
uma pessoa. No vídeo utilizado, a transação é realizada sem quaisquer falhas.
Frases dos estudantes:

 -"Eu tenho que testar isto!"
 -"Incrível!"
 -"Geente!"
 
 Em seguida, aproveitando a discussão do vídeo, eles 
 foram provocados a responder no ambiente do [slido](slido.com)
 **"Quais profissões você acha que estão ameaçadas pela IA?"**. 
 Alguns estudantes refletiram além da proposta, ao ponto de 
 sugerir que haveria a esperança da existência de 
 um exterminador do futuro. Outros disseram:
 
 - "Professor, concordo com quem diz que todas as profissões 
 estão ameçadas. Se a internet acabar todos estão perdidos."
 - "A internet agora é oxigênio, daqui a pouco os carros viram robô.
 
 A discussão foi amarrada pelo instrutor que conclui que a 
 maioria das profissões ameaçadas são aquelas que 
 estão ligadas a inteligência artificial fraca. Enquanto
 que outras profissões  serão cada vez mais necessárias. 
 
 Os estudantes ainda forneceram diversos outros exemplos 
 com os quais interagiram ou refletiram, como a capacidade 
 da inteligência artificial do Bradesco de identificar 
 termos inapropriados. O professor 
 mostrou as campanhas contra assédio por meio de IA. 
 
 Em outras situação uma 
 estudante vai mais a fundo na reflexão sobre empregos, 
 alcançando uma hipérbole econômica, ao pensar 
 que as máquinas dominariam todas as atividades de trabalho 
 e finalmente o que seria do homem?
 
 O instrutor conduz um pensamento sobre  
 a necessidade de dados de boa qualidade e a importância 
 do cientista de dados para evitar viéses dos modelos de IA. 
 
 Uma estudante faz uma analogia ao final do encontro, 
 dizendo que "a IA ainda é limitada pois não capaz de 
 se reprogramar, da mesma forma como não poderíamos mudar 
 o nosso cérebro."
 
 
 
 



 
 
## Fato ou Fake? 

Os avanços tecnológicos e a ampliação do universo de comunicação 
seja pela mídia jornalística ou redes sociais traz benefícios 
incontestáveis,  entretanto, o efeito colateral desse amplo acesso
é o surgimento de mecanismos de produção de notícias falsas. 
Neste encontro os estudantes foram provocados como a mídia 
digital está sujeita a estes ataques e como é possível 
a utilização de inteligência artificial para 
ajudar no combate deste universo. 

O encontro foi conduzido inicialmente pela elaboração de 
um jogo operado na plataforma [Kahoot!](https://kahoot.com/), 
no qual os estudantes foram estimulados a responder 
sobre notícias que são fato ou que são fake. 

 - Animais de estimação podem transmitir COVID-19 aos humanos.
 - Por engano mulher rezava  para boneco do "Senhor dos Anéis". 
 - Pedro Alvarez Cabral descobriu o Brasil.
 - DNA do homem é $50%$ idêntico ao DNA da Banana.
 - Participantes de um programa *reality* passam um ano isolados, 
 mas apenas parte do programa foi exibido.
 - Medir neurônios pela testa mata neurônios.
 - Universidade cria museu de memes. 
 - Usar álcool gel nas mãos para prevenção da COVID-19, 
 altera o resultado no teste do bafômetro em blitze. 
 
 
 Dessa maneira, os estudantes são colocados na posição 
 de decisão, similar a função que se pretendia 
 discutir nas etapas posteriores sobre o papel da 
 inteligência artificial em nos apoiar em decisões 
 sobre a veracidade de informações da internet ou redes sociais. 
 
 Para auxiliar nesta reflexão foi solicitado aos 
 estudantes que indicassem quais melhores 
 práticas para evitar as notícias falsas. Alguns 
 estudantes indicaram a seguintes práticas para 
 indicar se é ou não a *fake news*:
 
 - "Procurar se as fontes as fontes são seguras."
 - "Pesquisar, analisar a fonte."
 
 O instrutor indicou as seguintes práticas:
 
 - erros ortográficos;
 - concordâncias erradas; 
 - verificar se as informações desatualizadas;
 - suspeitar da forma de difusão da informação que são acompanhadas de estímulos de 
 compartilhamento;
 - duvidar de notícias alarmistas.
 
 
 Depois de uma ampla discussão sobre a veracidade de notícias, 
 foi gerado uma prática no [slido](http://slido.com) que solicitava 
 quem eram as pessoas conhecidas ou parentes que mais compartilham "fake news".
 Em geral, "Mãe" e  "Grupo da Família" chamam muito atenção. Na opinião dos 
 estudantes os pais e avós que não cresceram com uso de tecnologia tem mais 
 dificuldade em determinar se uma notícia é ou não *fake news*. 
 Chegaram a conclusão que pessoas com o menor grau de educação tem mais 
 dificuldade em decidir sobre a veracidade das notícias. Também 
 foi explorado qual a região do país que mais acreditam em *fake news* 
 a respeito de COVID-19.
 
 Finalmente, depois de contextualizá-los, foi proposto o debate 
 sobre a aplicação da inteligência artificial na identificação de *fake news*.
 Por meio do resultado de uma pesquisa que desenvolveu um aplicação AI
 que aprende a construir *fake news* para em seguida decidir o que era
 ou não *fake news*, os estudantes passaram a notar que o papel de decisão 
 assumidos por eles na primeira etapa do do encontro, agora estava automatizado.
 
 Para demonstrar  o potencial do ferramental de AI que  
 para a produção de *fake news*, foi demonstrado o conceito de "deepfake"
 no qual foi exemplificado pelo app deepface. Demonstrando como 
 pode ser divertido e igualmente arriscado, podendo intereferir na 
 vida de indivíduos e até mesmo na relação entre países, por exemplo com 
 a produção de aúdios falsos associados a políticos. 
 
 Para a compreensão do mecanismos de funcionamento da construção de 
 frases por meio de IA foi apresentado um diagrama esquemático 
 constituído das principais  etapas: 
 
  - Banco de palavras chave;
  - Conversão de palavras em números;
  - Combinação dos números;
  - Classificação, atribuição de rótulo.
  
  Um pequeno debate sobre a importância da escolha de 
  verbos, substântivos e de maneira indireta a respeito 
  da semântica entorno da construção e identificação de 
  *fake news*.
  
  Para que os estudantes não construam de maneira equivocada 
  a ideia de que a IA é um algorítimo utilizado apenas 
  para a construção de *fake news*, por meio
  do uso do [Scratch - Positividade](https://scratch.mit.edu/projects/510980026),
  desenvolvido pelo instrutor,
  os estudantes tiveram a experiência 
  do uso de um gerador de positividade. Um algorítimo 
  que contém um banco de frases que são combinadas de forma 
  aleatória. Os estudantes foram estimulados 
  a preencher um formulário para tornar este "robô" mais 
  inteligente. A medida que as frases são emitidas 
  o usuário as avalia como "gostei" ou "não gostei"
  reforçando o aprendizado. 
  
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
